### ISSUE TITLE
Cutting Crystal CPU into Raw Crystal Chip takes a TINY amount of Lubricant/Water

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCEu/gregicality#104]
![2020-07-14_09 46 38](https://user-images.githubusercontent.com/35029480/87398990-01511700-c5b7-11ea-8a8f-4dc5c285228c.png)

It takes a TINY amount of Fluid, needs to be increased by a lot, also why does this recipe take an engraved Crystal CPU (from Laser Engraver) instead of an Engraved Chip (from EBF) which makes no sense. Need Laser Engraver to make one to cut but not for Circuits? What even?

**Comment by DStrand1** [comment]
Closed as of GTCEu
