### ISSUE TITLE
[Suggestion] UHV+ Wireless Power

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCEu/gregicality#158]
I would love to see completely wireless power transmission at this stage of the game with some kind of large Multiblock Structure to send/receive energy, maybe an "upgraded" Battery Tower? It would have a certain range (maybe add some kind of block in the Multi that has different tiers for range) and Pylons to extend the range in a certain area. At this point pretty much all the machines should be Multiblocks so it would make sense to add Wireless Power Hatches that are connected to the Tower/a Pylon.

**Comment by Shattered2909** [comment]
I would go with some kind of Emitter Block and make this Multiblock take UHV or above.

**Comment by Zalgo239** [comment]
Here's my take on wireless power transfer:

A large tesla coil multiblock, capable of transmitting power to machines (possibly if those are given a special receiver upgrade).

What I think the basic one could look like:
![2020-09-08_20 05 01](https://user-images.githubusercontent.com/67443118/92514225-d6c7b700-f211-11ea-88dd-f47b5fd2fac7.png)

And view from the top:
![2020-09-08_20 25 56](https://user-images.githubusercontent.com/67443118/92514259-e3e4a600-f211-11ea-996d-0306a313b7a7.png)

The base could be made of pretty much any block (an insulator would be preferred), the base supports the primary coil (large circle of coil blocks) and the secondary coil (tall tower wrapped in coil blocks)
The tower itself is made of polyethylene blocks with coils wrapped around and as seen in the top view it is empty
The torus at the top should be made of a conductive and possibly heat resistant block

The coil should transmit power to nearby machines with an efficiency that goes down according to the inverse square law.
To upgrade the transmitted power the player should swap the coils with higher tier ones to transmit an higher total amperage (the sum of all the amps consumed by all machines drawing power from the coil). Swapping the coils could also allow the player to transmit a higher voltage tier
To upgrade the range the player should make the tower higher, realistically the max range should scale with the square root of the height, this would also make extremely tall coils unpractical.

The coil could also have a secondary operational mode, in this mode it is unable to provide power to machines, but it can shock mobs and players(it would need a whitelist/blacklist) from a longer range than the normal tesla coil block. Using higher tier coils deals more damage, and making the tower higher increased the max range like in the other operational mode
