### ISSUE TITLE
SMD Rework

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCEu/gregicality#224]
I am using a list that was given to me by Lord Pine, keep that in mind.
So, first of all it would make sense to rename the baseline GTCE SMD to Micro SMD to avoid confusion with Refined being below SMD.

I highly recommend removing the recipes for upgrading SMD because those take less ingredients (might allow tier skipping) and also create a chain that should not really be there. Another thing would be higher tier Plastics for higher tier SMD.

For Refined:
Diode: 8 Fine Gold Wire + 1 Gallium Arsenide Dust + 144mb PET = 8 Refined SMD Diodes (Diodes are needed a lot less than other parts)
Capacitor: 4 Polyethylene Foil + 2 Tantalum Foil +144mb PET = 16 Refined SMD Capacitors
Resistor: 8 Fine Annealed Copper Wire + 1 Manganese Dioxide Dust (MnO2) + 144mb PET = 16 Refined SMD Resistors
Transistor: 8 Fine Annealed Copper Wire + 1 Ni-Silicide Plate (2 Nickel 1 Silicon Alloy, needs EBF) + 144mb PET = 16 Refined SMD Transistors

These recipes are implemented in my pack right now (with some small differences which I changed my mind on recently) so they are ready.

The tiers above are not really done yet but Lord Pine gave me this list for ideas: https://pastebin.com/ujb6XkC1
These are different materials that would make sense in the recipes of these components.

**Comment by huneau** [comment]
If I resume actually to make a circuit C you need:
C = ( x * SMD T) 
C = ( 2x * SMD T-1) 
and 
x * SMD T = RAW Material T * y
x/2 * SMD T = RAW Material T-1 * y + z SMD T-1

so @Shattered2909 you dislike: 
x/2 * SMD T = RAW Material T-1 * y + z SMD T-1 
right ?

how can I make a tiered recipe for SMD/C or balanced it?

**Comment by pablocnvs** [comment]
The materials in that list are done in my latest PR, so it is just a matter of choosing which ones we want and adjust accordingly.

**Comment by pablocnvs** [comment]
Unless anyone has any objections, we can close this issue.

**Comment by DStrand1** [comment]
Closed as not relevant in GTCEu versions of Gregicality, since SMDs are being overhauled
