### ISSUE TITLE
[Suggestion] Motor Materials

### ISSUE THREAD

**Issue by Shattered2909** [GregTechCEu/gregicality#245]
At the moment, all of the Motors (until very late) all take Copper which on one hand does not make a huge amount of sense when higher Voltage Wires exist, on the other hand it gets really annoying to farm huge amounts of Copper later, so I propose this change:
LV Motors take Tin Wire instead of Copper
MV Motors still use Copper
HV Electrum
EV Aluminium
IV Platinum

I do not know which ones to use at LuV and above, guess at LuV the options are Yttrium-Barium-Cuprate, Niobium-Titanium and Vanadium-Gallium, probably best to go with Niobium-Titanium for the Wires.

ZPM does not have a lot of Wire Materials, maybe just Naquadah?

**Comment by Regian24** [comment]
I have a list of all wires here: https://docs.google.com/spreadsheets/d/1dwIlB7ZJoNUdlahWejym8nCjq1sdCzrMEJ46GKqgF4Y/edit#gid=0 , it could be helpful.

**Comment by DStrand1** [comment]
Closed as of GTCEu
