### ISSUE TITLE
[Suggestion] fission material

### ISSUE THREAD

**Issue by Pnc6lx** [GregTechCEu/gregicality#409]
gregicality have many fission materials, nuclear craft also have many kind fission materials.
1. Some materials have same name, but have different ore dictionary. for example, U235: Nuclear craft is Uranium235, while gregicality is Uranium235Isotope. I want to know why it is, and hope it can use it in both mods. 
2. some NC fission material dont have their gregicality form, i hope they can use in gregicality fisson reactor

**Comment by Pnc6lx** [comment]
edit: U235 and 238 have same ore dictionary, U233 is UraniumRadioactive233

**Comment by hjae78** [comment]
Do NuclearCraft have ingots of those isotopes? If so I can change the oredict of our materials to match

**Comment by Pnc6lx** [comment]
> Do NuclearCraft have ingots of those isotopes? If so I can change the oredict of our materials to match

yes， their isotopes have ingot form.
![image](https://user-images.githubusercontent.com/49830847/111562601-6bb6f880-87d1-11eb-8feb-dca7c45b2dd7.png)
their are all form a isotope in NuclearCraft: Overhauled. NucearCraft dont have ingotUranium233Carbide, ingotUranium233Nitride, ingotUranium233ZA. -All. -Carbide, -Nitride, -Oxide, -ZA( mean zirconium alloy) are their fisson fuel forms, so its not important to add such form.
