### ISSUE TITLE
[Suggestion] TFC FRESH water using in GT steam boilers

### ISSUE THREAD

**Issue by SpeeeDCraft** [GregTechCEu/gregicality#418]
Adding the use of not only vanilla water in boilers, but also, for example, fresh TerraFirmaCraft water, this would greatly improve my modpack with TerraFirmaCraft + GregTech + Gregicality.

**Comment by brachy84** [comment]
The water is hardcoded in gregtech [here](https://github.com/GregTechCE/GregTech/blob/e812e4669feaf220d8eb7b5fbb6ea1ebe0f805bc/src/main/java/gregtech/api/recipes/ModHandler.java#L50), which gets called from [here](https://github.com/GregTechCE/GregTech/blob/e812e4669feaf220d8eb7b5fbb6ea1ebe0f805bc/src/main/java/gregtech/common/metatileentities/steam/boiler/SteamBoiler.java#L252). I don't know if we can do it in Gregicality.

**Comment by SpeeeDCraft** [comment]
Good. I also wrote to the gt developers.

**Comment by SpeeeDCraft** [comment]
Fixed here https://github.com/GregTechCEu/GregTech/commit/1382f97016e12c19bc473c164caca6d31981edd8
