### ISSUE TITLE
make large machinery to share functional blocks

### ISSUE THREAD

**Issue by vfyjxf** [GregTechCEu/gregicality#48]
make large machinery to share like Input Hatch or Input Bus

**Comment by hjae78** [comment]
I'm not sure what you're asking

**Comment by huneau** [comment]
![image](https://user-images.githubusercontent.com/9199240/84565649-c6b34f00-ad6a-11ea-99c1-80164c649c4f.png)
you cannot do that

**Comment by DStrand1** [comment]
Closed as of GTCEu
