### ISSUE TITLE
[Suggestion] Type Filter

### ISSUE THREAD

**Issue by RealRedCraft86** [GregTechCEu/gregicality#484]
Tbh, a [Type Filter(which is from GT5)](https://ftb.fandom.com/wiki/Type_Filter) would be very useful and I have a feeling GTCE is never gonna add it in.

**Comment by warjort** [comment]
Why isn't the ore dictionary filter not the same thing or more flexible?
https://imgur.com/gallery/D7aCtlV

**Comment by RealRedCraft86** [comment]
Last time I checked, when you filter dust, tiny dust also gets filtered

**Comment by ALongStringOfNumbers** [comment]
> 
> 
> Last time I checked, when you filter dust, tiny dust also gets filtered, and its annoying the shit out of me

There was a new oredict added to full size dusts, `dustRegular` that allows for the full size dusts to be separated from others

**Comment by RealRedCraft86** [comment]
hmm, in that case then, it might be ok, if this doesn't get added
