### ISSUE TITLE
Change circuit board naming conventions to better reflect on processing lines and technological progression

### ISSUE THREAD

**Issue by ghost** [GregTechCEu/gregicality#538]
Currently, the GTCE circuit boards act more as substrates for the finished circuit boards used in Gregicality. However, they are still named "circuit boards" in addition to the Gregicality circuit boards, which doesn't make sense considering their use in Gregicality.

To remove this ambiguity and make circuit board tiering easier to follow, the GTCE boards should be renamed to "X Board Substrate", where X is the primary material(s) used in the substrate, e.g. "Phenolic Circuit Board" -> "Phenolic Board Substrate"

The circuit boards in Gregicality should also be named after their respective "technology tier," e.g. "Good Plastic Circuit Board" -> "Refined Circuit Board"

**Comment by DStrand1** [comment]
Closing as resolved by GTCEu
