### ISSUE TITLE
[Suggestion]Config for updated save compatibility.

### ISSUE THREAD

**Issue by Blue-Beaker** [GregTechCEu/gregicality#603]
I played 0.22 before and when I update to 0.23 most of my multiblock machines needs to be changed a lot.
In 0.23, most multiblock changed their shape, and maintenance hatch became a required block, and muffler hatch is also a required block for some multiblocks. But most of my multiblock machines shares a lot of blocks and they can't even fit a single more hatch nor a larger model unless rebuild the most of the factory.
I suggest to add some config options:
1. use legacy machine models: use those multiblock structures in 0.22.7(new multiblocks remains unchanged), but both new and old casings are accepted, new hatches remains needed unless individually disabled
2. maintenance hatch needed: when set to false the maintenance hatch will not be needed in every multiblock. if not present the maintenance problems can't be fixed.
3. muffler hatch needed: when false muffler hatch won't be needed. If not present in a multiblock, disables auxliary outputs for it.

**Comment by DStrand1** [comment]
Unfortunately, most of this won't be possible to do, especially the first suggestion. The other two could technically be possible, but it is intended for those to be necessary now
